# Generated by Django 5.2.13 on 2026-04-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("techno", "Techno"),
                            ("house", "House"),
                            ("deep_house", "Deep House"),
                            ("tech_house", "Tech House"),
                            ("minimal", "Minimal"),
                            ("melodic_techno", "Melodic Techno / House"),
                            ("drum_and_bass", "Drum & Bass"),
                            ("ambient", "Ambient"),
                            ("trance", "Trance"),
                            ("progressive", "Progressive"),
                            ("electro", "Electro"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("instagram", models.CharField(blank=True, max_length=200)),
                ("soundcloud", models.CharField(blank=True, max_length=200)),
                (
                    "demo_submission_url",
                    models.URLField(
                        blank=True, help_text="Demo submission portal URL if available"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("techno", "Techno"),
                            ("house", "House"),
                            ("deep_house", "Deep House"),
                            ("tech_house", "Tech House"),
                            ("minimal", "Minimal"),
                            ("melodic_techno", "Melodic Techno / House"),
                            ("drum_and_bass", "Drum & Bass"),
                            ("ambient", "Ambient"),
                            ("trance", "Trance"),
                            ("progressive", "Progressive"),
                            ("electro", "Electro"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("bpm", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "key",
                    models.CharField(
                        blank=True, help_text="e.g. Am, F#m, G Major", max_length=20
                    ),
                ),
                (
                    "duration",
                    models.CharField(blank=True, help_text="e.g. 6:30", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("demo", "Demo"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                            ("released", "Released"),
                            ("shelved", "Shelved"),
                        ],
                        default="demo",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="tracks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("no_response", "No Response"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_date", models.DateField(blank=True, null=True)),
                (
                    "terms",
                    models.TextField(
                        blank=True,
                        help_text="Deal terms if accepted (e.g. revenue split, exclusivity period, release date)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any notes about this submission or the label's response",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="crm.label",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="crm.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_date"],
                "unique_together": {("track", "label")},
            },
        ),
    ]
